export const PORTUGUESE_WORDS_EASY = [
  { word: 'abacaxi', hint: 'fruta' },
  { word: 'computador', hint: 'objeto' },
  { word: 'javascript', hint: 'tecnologia' },
  { word: 'igreja', hint: 'lugar' },
  { word: 'celular', hint: 'objeto' },
  { word: 'internet', hint: 'tecnologia' },
  { word: 'teclado', hint: 'objeto' },
  { word: 'monitor', hint: 'objeto' },
  { word: 'mouse', hint: 'objeto' },
  { word: 'cadeira', hint: 'objeto' },

  { word: 'janela', hint: 'objeto' },
  { word: 'porta', hint: 'objeto' },
  { word: 'livro', hint: 'objeto' },
  { word: 'caneta', hint: 'objeto' },
  { word: 'caderno', hint: 'objeto' },
  { word: 'escola', hint: 'lugar' },
  { word: 'professor', hint: 'pessoa' },
  { word: 'aluno', hint: 'pessoa' },
  { word: 'cidade', hint: 'lugar' },
  { word: 'praia', hint: 'lugar' },

  { word: 'montanha', hint: 'natureza' },
  { word: 'rio', hint: 'natureza' },
  { word: 'floresta', hint: 'natureza' },
  { word: 'carro', hint: 'objeto' },
  { word: 'bicicleta', hint: 'objeto' },
  { word: 'aviao', hint: 'objeto' },
  { word: 'onibus', hint: 'objeto' },
  { word: 'trem', hint: 'objeto' },
  { word: 'barco', hint: 'objeto' },
  { word: 'navio', hint: 'objeto' },

  { word: 'cachorro', hint: 'animal' },
  { word: 'gato', hint: 'animal' },
  { word: 'passaro', hint: 'animal' },
  { word: 'peixe', hint: 'animal' },
  { word: 'leao', hint: 'animal' },
  { word: 'tigre', hint: 'animal' },
  { word: 'elefante', hint: 'animal' },
  { word: 'girafa', hint: 'animal' },
  { word: 'macaco', hint: 'animal' },
  { word: 'cobra', hint: 'animal' },

  { word: 'futebol', hint: 'atividade' },
  { word: 'basquete', hint: 'atividade' },
  { word: 'volei', hint: 'atividade' },
  { word: 'tenis', hint: 'atividade' },
  { word: 'corrida', hint: 'atividade' },
  { word: 'natacao', hint: 'atividade' },
  { word: 'musica', hint: 'arte' },
  { word: 'filme', hint: 'arte' },
  { word: 'teatro', hint: 'arte' },
  { word: 'pintura', hint: 'arte' },

  { word: 'laranja', hint: 'fruta' },
  { word: 'manga', hint: 'fruta' },
  { word: 'melancia', hint: 'fruta' },
  { word: 'uva', hint: 'fruta' },
  { word: 'pera', hint: 'fruta' },
  { word: 'morango', hint: 'fruta' },
  { word: 'limao', hint: 'fruta' },
  { word: 'goiaba', hint: 'fruta' },
  { word: 'coco', hint: 'fruta' },
  { word: 'kiwi', hint: 'fruta' },

  { word: 'geladeira', hint: 'objeto' },
  { word: 'fogao', hint: 'objeto' },
  { word: 'microondas', hint: 'objeto' },
  { word: 'ventilador', hint: 'objeto' },
  { word: 'televisao', hint: 'objeto' },
  { word: 'controle', hint: 'objeto' },
  { word: 'sofa', hint: 'objeto' },
  { word: 'mesa', hint: 'objeto' },
  { word: 'armario', hint: 'objeto' },
  { word: 'espelho', hint: 'objeto' },

  { word: 'hospital', hint: 'lugar' },
  { word: 'farmacia', hint: 'lugar' },
  { word: 'mercado', hint: 'lugar' },
  { word: 'restaurante', hint: 'lugar' },
  { word: 'padaria', hint: 'lugar' },
  { word: 'biblioteca', hint: 'lugar' },
  { word: 'parque', hint: 'lugar' },
  { word: 'aeroporto', hint: 'lugar' },
  { word: 'rodoviaria', hint: 'lugar' },
  { word: 'estadio', hint: 'lugar' },

  { word: 'medico', hint: 'pessoa' },
  { word: 'engenheiro', hint: 'pessoa' },
  { word: 'advogado', hint: 'pessoa' },
  { word: 'motorista', hint: 'pessoa' },
  { word: 'cozinheiro', hint: 'pessoa' },
  { word: 'bombeiro', hint: 'pessoa' },
  { word: 'policial', hint: 'pessoa' },
  { word: 'cantor', hint: 'pessoa' },
  { word: 'ator', hint: 'pessoa' },
  { word: 'pintor', hint: 'pessoa' },

  { word: 'chuva', hint: 'natureza' },
  { word: 'vento', hint: 'natureza' },
  { word: 'neve', hint: 'natureza' },
  { word: 'tempestade', hint: 'natureza' },
  { word: 'relampago', hint: 'natureza' },
  { word: 'trovão', hint: 'natureza' },
  { word: 'sol', hint: 'natureza' },
  { word: 'lua', hint: 'natureza' },
  { word: 'estrela', hint: 'natureza' },
  { word: 'oceano', hint: 'natureza' }
];

export const PORTUGUESE_WORDS_MEDIUM = [
  { word: 'paralelepipedo', hint: 'objeto' },
  { word: 'inconstitucional', hint: 'conceito' },
  { word: 'otorrinolaringologista', hint: 'pessoa' },
  { word: 'anticonstitucional', hint: 'conceito' },
  { word: 'eletroencefalograma', hint: 'objeto' },
  { word: 'interdisciplinaridade', hint: 'conceito' },
  { word: 'hipopotomonstrosesquipedaliofobia', hint: 'conceito' },
  { word: 'desenvolvimento', hint: 'conceito' },
  { word: 'responsabilidade', hint: 'conceito' },
  { word: 'caracteristica', hint: 'conceito' },

  { word: 'extraordinario', hint: 'conceito' },
  { word: 'inacreditavel', hint: 'conceito' },
  { word: 'impressionante', hint: 'conceito' },
  { word: 'irreversivel', hint: 'conceito' },
  { word: 'indispensavel', hint: 'conceito' },
  { word: 'incompreensivel', hint: 'conceito' },
  { word: 'inevitavel', hint: 'conceito' },
  { word: 'inquestionavel', hint: 'conceito' },
  { word: 'insubstituivel', hint: 'conceito' },
  { word: 'incontrolavel', hint: 'conceito' },

  { word: 'bibliotecario', hint: 'pessoa' },
  { word: 'arqueologo', hint: 'pessoa' },
  { word: 'psicologo', hint: 'pessoa' },
  { word: 'dermatologista', hint: 'pessoa' },
  { word: 'cardiologista', hint: 'pessoa' },
  { word: 'neurologista', hint: 'pessoa' },
  { word: 'oftalmologista', hint: 'pessoa' },
  { word: 'endocrinologista', hint: 'pessoa' },
  { word: 'nutricionista', hint: 'pessoa' },
  { word: 'fisioterapeuta', hint: 'pessoa' },

  { word: 'laboratorio', hint: 'lugar' },
  { word: 'universidade', hint: 'lugar' },
  { word: 'observatorio', hint: 'lugar' },
  { word: 'planetario', hint: 'lugar' },
  { word: 'anfiteatro', hint: 'lugar' },
  { word: 'auditorio', hint: 'lugar' },
  { word: 'instituicao', hint: 'lugar' },
  { word: 'organizacao', hint: 'lugar' },
  { word: 'estabelecimento', hint: 'lugar' },
  { word: 'infraestrutura', hint: 'conceito' },

  { word: 'metamorfose', hint: 'natureza' },
  { word: 'biodiversidade', hint: 'natureza' },
  { word: 'ecossistema', hint: 'natureza' },
  { word: 'fotossintese', hint: 'natureza' },
  { word: 'polinizacao', hint: 'natureza' },
  { word: 'desmatamento', hint: 'natureza' },
  { word: 'reflorestamento', hint: 'natureza' },
  { word: 'sustentabilidade', hint: 'conceito' },
  { word: 'aquecimento', hint: 'natureza' },
  { word: 'climatologia', hint: 'natureza' },

  { word: 'criptografia', hint: 'tecnologia' },
  { word: 'inteligencia', hint: 'tecnologia' },
  { word: 'artificial', hint: 'tecnologia' },
  { word: 'programacao', hint: 'tecnologia' },
  { word: 'desenvolvedor', hint: 'pessoa' },
  { word: 'algoritmo', hint: 'tecnologia' },
  { word: 'framework', hint: 'tecnologia' },
  { word: 'biblioteca', hint: 'tecnologia' },
  { word: 'compilador', hint: 'tecnologia' },
  { word: 'interpretador', hint: 'tecnologia' },

  { word: 'revolucionario', hint: 'conceito' },
  { word: 'tradicionalismo', hint: 'conceito' },
  { word: 'modernizacao', hint: 'conceito' },
  { word: 'industrializacao', hint: 'conceito' },
  { word: 'globalizacao', hint: 'conceito' },
  { word: 'urbanizacao', hint: 'conceito' },
  { word: 'colonizacao', hint: 'conceito' },
  { word: 'independencia', hint: 'conceito' },
  { word: 'democracia', hint: 'conceito' },
  { word: 'republica', hint: 'conceito' },

  { word: 'conhecimento', hint: 'conceito' },
  { word: 'aprendizado', hint: 'conceito' },
  { word: 'raciocinio', hint: 'conceito' },
  { word: 'pensamento', hint: 'conceito' },
  { word: 'compreensao', hint: 'conceito' },
  { word: 'interpretacao', hint: 'conceito' },
  { word: 'percepcao', hint: 'conceito' },
  { word: 'criatividade', hint: 'conceito' },
  { word: 'imaginacao', hint: 'conceito' },
  { word: 'sabedoria', hint: 'conceito' },

  { word: 'administracao', hint: 'conceito' },
  { word: 'planejamento', hint: 'conceito' },
  { word: 'organizacao', hint: 'conceito' },
  { word: 'estrategia', hint: 'conceito' },
  { word: 'lideranca', hint: 'conceito' },
  { word: 'produtividade', hint: 'conceito' },
  { word: 'eficiencia', hint: 'conceito' },
  { word: 'qualidade', hint: 'conceito' },
  { word: 'inovacao', hint: 'conceito' },
  { word: 'competitividade', hint: 'conceito' }

]

export const PORTUGUESE_WORDS_HARD = [
  { word: 'inconstitucionalissimamente', hint: 'conceito' },
  { word: 'otorrinolaringologico', hint: 'pessoa' },
  { word: 'anticonstitucionalissimamente', hint: 'conceito' },
  { word: 'hipopotomonstrosesquipedaliofobia', hint: 'conceito' },
  { word: 'pneumoultramicroscopicosilicovulcanoconiose', hint: 'doenca' },

  { word: 'desoxirribonucleico', hint: 'ciencia' },
  { word: 'eletroencefalografista', hint: 'pessoa' },
  { word: 'paraclorobenzilpirrolidinonetilbenzimidazol', hint: 'quimica' },
  { word: 'antropomorfizacao', hint: 'conceito' },
  { word: 'interdisciplinaridade', hint: 'conceito' },

  { word: 'transubstanciacao', hint: 'conceito' },
  { word: 'incomensurabilidade', hint: 'conceito' },
  { word: 'contrarrevolucionario', hint: 'conceito' },
  { word: 'desproporcionalidade', hint: 'conceito' },
  { word: 'imprevisibilidade', hint: 'conceito' },

  { word: 'metalinguisticamente', hint: 'conceito' },
  { word: 'epistemologicamente', hint: 'conceito' },
  { word: 'hermeneuticamente', hint: 'conceito' },
  { word: 'ontologicamente', hint: 'conceito' },
  { word: 'fenomenologicamente', hint: 'conceito' },

  { word: 'neuropsicofarmacologico', hint: 'ciencia' },
  { word: 'psiconeuroendocrinologia', hint: 'ciencia' },
  { word: 'imunohistoquimica', hint: 'ciencia' },
  { word: 'eletrocardiograma', hint: 'objeto' },
  { word: 'ultrassonografia', hint: 'objeto' },

  { word: 'constitucionalidade', hint: 'conceito' },
  { word: 'incompatibilidade', hint: 'conceito' },
  { word: 'irreconciliavel', hint: 'conceito' },
  { word: 'indissociabilidade', hint: 'conceito' },
  { word: 'incomunicabilidade', hint: 'conceito' },

  { word: 'descaracterizacao', hint: 'conceito' },
  { word: 'desregulamentacao', hint: 'conceito' },
  { word: 'superdimensionamento', hint: 'conceito' },
  { word: 'subdesenvolvimento', hint: 'conceito' },
  { word: 'hiperconectividade', hint: 'tecnologia' },

  { word: 'microprocessador', hint: 'tecnologia' },
  { word: 'desfragmentacao', hint: 'tecnologia' },
  { word: 'virtualizacao', hint: 'tecnologia' },
  { word: 'containerizacao', hint: 'tecnologia' },
  { word: 'orquestracao', hint: 'tecnologia' },

  { word: 'criptograficamente', hint: 'tecnologia' },
  { word: 'deserializacao', hint: 'tecnologia' },
  { word: 'autenticacao', hint: 'tecnologia' },
  { word: 'autorregulamentacao', hint: 'conceito' },
  { word: 'responsabilizacao', hint: 'conceito' },

  { word: 'interoperabilidade', hint: 'tecnologia' },
  { word: 'escalabilidade', hint: 'tecnologia' },
  { word: 'confiabilidade', hint: 'conceito' },
  { word: 'disponibilidade', hint: 'conceito' },
  { word: 'manutenibilidade', hint: 'conceito' }
];

export const ENGLISH_WORDS_EASY = [
  { word: 'apple', hint: 'fruit' },
  { word: 'banana', hint: 'fruit' },
  { word: 'grape', hint: 'fruit' },
  { word: 'orange', hint: 'fruit' },
  { word: 'lemon', hint: 'fruit' },
  { word: 'peach', hint: 'fruit' },
  { word: 'pear', hint: 'fruit' },
  { word: 'melon', hint: 'fruit' },
  { word: 'mango', hint: 'fruit' },
  { word: 'berry', hint: 'fruit' },

  { word: 'dog', hint: 'animal' },
  { word: 'cat', hint: 'animal' },
  { word: 'bird', hint: 'animal' },
  { word: 'fish', hint: 'animal' },
  { word: 'lion', hint: 'animal' },
  { word: 'tiger', hint: 'animal' },
  { word: 'horse', hint: 'animal' },
  { word: 'sheep', hint: 'animal' },
  { word: 'cow', hint: 'animal' },
  { word: 'duck', hint: 'animal' },

  { word: 'car', hint: 'object' },
  { word: 'bus', hint: 'object' },
  { word: 'bike', hint: 'object' },
  { word: 'train', hint: 'object' },
  { word: 'plane', hint: 'object' },
  { word: 'boat', hint: 'object' },
  { word: 'chair', hint: 'object' },
  { word: 'table', hint: 'object' },
  { word: 'bed', hint: 'object' },
  { word: 'door', hint: 'object' },

  { word: 'house', hint: 'place' },
  { word: 'school', hint: 'place' },
  { word: 'park', hint: 'place' },
  { word: 'store', hint: 'place' },
  { word: 'beach', hint: 'place' },
  { word: 'city', hint: 'place' },
  { word: 'farm', hint: 'place' },
  { word: 'zoo', hint: 'place' },
  { word: 'road', hint: 'place' },
  { word: 'room', hint: 'place' },

  { word: 'man', hint: 'person' },
  { word: 'woman', hint: 'person' },
  { word: 'child', hint: 'person' },
  { word: 'friend', hint: 'person' },
  { word: 'teacher', hint: 'person' },
  { word: 'doctor', hint: 'person' },
  { word: 'driver', hint: 'person' },
  { word: 'farmer', hint: 'person' },
  { word: 'worker', hint: 'person' },
  { word: 'player', hint: 'person' },

  { word: 'run', hint: 'action' },
  { word: 'walk', hint: 'action' },
  { word: 'jump', hint: 'action' },
  { word: 'eat', hint: 'action' },
  { word: 'drink', hint: 'action' },
  { word: 'sleep', hint: 'action' },
  { word: 'read', hint: 'action' },
  { word: 'write', hint: 'action' },
  { word: 'play', hint: 'action' },
  { word: 'watch', hint: 'action' },

  { word: 'red', hint: 'color' },
  { word: 'blue', hint: 'color' },
  { word: 'green', hint: 'color' },
  { word: 'yellow', hint: 'color' },
  { word: 'black', hint: 'color' },
  { word: 'white', hint: 'color' },
  { word: 'pink', hint: 'color' },
  { word: 'brown', hint: 'color' },
  { word: 'gray', hint: 'color' },
  { word: 'purple', hint: 'color' },

  { word: 'sun', hint: 'nature' },
  { word: 'moon', hint: 'nature' },
  { word: 'star', hint: 'nature' },
  { word: 'sky', hint: 'nature' },
  { word: 'tree', hint: 'nature' },
  { word: 'river', hint: 'nature' },
  { word: 'lake', hint: 'nature' },
  { word: 'sea', hint: 'nature' },
  { word: 'rain', hint: 'nature' },
  { word: 'wind', hint: 'nature' }
];

export const ENGLISH_WORDS_MEDIUM = [
  { word: 'architecture', hint: 'concept' },
  { word: 'development', hint: 'concept' },
  { word: 'responsibility', hint: 'concept' },
  { word: 'characteristic', hint: 'concept' },
  { word: 'communication', hint: 'concept' },
  { word: 'environment', hint: 'nature' },
  { word: 'temperature', hint: 'nature' },
  { word: 'information', hint: 'concept' },
  { word: 'technology', hint: 'technology' },
  { word: 'application', hint: 'technology' },

  { word: 'programming', hint: 'technology' },
  { word: 'algorithm', hint: 'technology' },
  { word: 'database', hint: 'technology' },
  { word: 'framework', hint: 'technology' },
  { word: 'interface', hint: 'technology' },
  { word: 'repository', hint: 'technology' },
  { word: 'deployment', hint: 'technology' },
  { word: 'integration', hint: 'technology' },
  { word: 'authentication', hint: 'technology' },
  { word: 'authorization', hint: 'technology' },

  { word: 'psychology', hint: 'science' },
  { word: 'philosophy', hint: 'science' },
  { word: 'sociology', hint: 'science' },
  { word: 'anthropology', hint: 'science' },
  { word: 'neurology', hint: 'science' },
  { word: 'cardiology', hint: 'science' },
  { word: 'dermatology', hint: 'science' },
  { word: 'epistemology', hint: 'concept' },
  { word: 'metaphysics', hint: 'concept' },
  { word: 'phenomenology', hint: 'concept' },

  { word: 'extraordinary', hint: 'concept' },
  { word: 'unbelievable', hint: 'concept' },
  { word: 'incredible', hint: 'concept' },
  { word: 'impossible', hint: 'concept' },
  { word: 'unpredictable', hint: 'concept' },
  { word: 'irreversible', hint: 'concept' },
  { word: 'indispensable', hint: 'concept' },
  { word: 'incomprehensible', hint: 'concept' },
  { word: 'uncontrollable', hint: 'concept' },
  { word: 'unquestionable', hint: 'concept' },

  { word: 'organization', hint: 'concept' },
  { word: 'administration', hint: 'concept' },
  { word: 'management', hint: 'concept' },
  { word: 'productivity', hint: 'concept' },
  { word: 'efficiency', hint: 'concept' },
  { word: 'innovation', hint: 'concept' },
  { word: 'creativity', hint: 'concept' },
  { word: 'imagination', hint: 'concept' },
  { word: 'knowledge', hint: 'concept' },
  { word: 'understanding', hint: 'concept' },

  { word: 'transportation', hint: 'object' },
  { word: 'communication', hint: 'concept' },
  { word: 'electricity', hint: 'concept' },
  { word: 'refrigerator', hint: 'object' },
  { word: 'microwave', hint: 'object' },
  { word: 'television', hint: 'object' },
  { word: 'calculator', hint: 'object' },
  { word: 'controller', hint: 'object' },
  { word: 'instrument', hint: 'object' },
  { word: 'equipment', hint: 'object' },

  { word: 'mountainous', hint: 'nature' },
  { word: 'vegetation', hint: 'nature' },
  { word: 'ecosystem', hint: 'nature' },
  { word: 'biodiversity', hint: 'nature' },
  { word: 'pollution', hint: 'nature' },
  { word: 'deforestation', hint: 'nature' },
  { word: 'sustainability', hint: 'concept' },
  { word: 'conservation', hint: 'nature' },
  { word: 'atmosphere', hint: 'nature' },
  { word: 'temperature', hint: 'nature' }
];

export const ENGLISH_WORDS_HARD = [
  { word: 'pneumonoultramicroscopicsilicovolcanoconiosis', hint: 'disease' },
  { word: 'hippopotomonstrosesquipedaliophobia', hint: 'concept' },
  { word: 'floccinaucinihilipilification', hint: 'concept' },
  { word: 'antidisestablishmentarianism', hint: 'concept' },
  { word: 'supercalifragilisticexpialidocious', hint: 'fiction' },

  { word: 'thyroparathyroidectomized', hint: 'science' },
  { word: 'dichlorodifluoromethane', hint: 'chemistry' },
  { word: 'incomprehensibilities', hint: 'concept' },
  { word: 'honorificabilitudinitatibus', hint: 'concept' },
  { word: 'psychoneuroendocrinological', hint: 'science' },

  { word: 'hepaticocholangiocholecystenterostomies', hint: 'medicine' },
  { word: 'spectrophotofluorometrically', hint: 'science' },
  { word: 'radioimmunoelectrophoresis', hint: 'science' },
  { word: 'electroencephalographically', hint: 'science' },
  { word: 'immunoelectrophoretically', hint: 'science' },

  { word: 'otorhinolaryngological', hint: 'science' },
  { word: 'psychophysicotherapeutics', hint: 'science' },
  { word: 'pathologicopsychological', hint: 'science' },
  { word: 'neuropharmacological', hint: 'science' },
  { word: 'microspectrophotometries', hint: 'science' },

  { word: 'counterrevolutionaries', hint: 'concept' },
  { word: 'institutionalizations', hint: 'concept' },
  { word: 'internationalization', hint: 'concept' },
  { word: 'hypercholesterolemia', hint: 'disease' },
  { word: 'electrocardiographically', hint: 'science' },

  { word: 'characteristically', hint: 'concept' },
  { word: 'disproportionateness', hint: 'concept' },
  { word: 'mischaracterization', hint: 'concept' },
  { word: 'overintellectualization', hint: 'concept' },
  { word: 'underrepresentation', hint: 'concept' },

  { word: 'cryptographically', hint: 'technology' },
  { word: 'misinterpretation', hint: 'concept' },
  { word: 'incompatibilities', hint: 'concept' },
  { word: 'intercommunication', hint: 'concept' },
  { word: 'overcompensation', hint: 'concept' },

  { word: 'subdermatoglyphic', hint: 'science' },
  { word: 'hexakosioihexekontahexaphobia', hint: 'concept' },
  { word: 'sesquipedalianism', hint: 'concept' },
  { word: 'otorhinolaryngologist', hint: 'person' },
  { word: 'laryngotracheobronchitis', hint: 'disease' },

  { word: 'psychopharmacological', hint: 'science' },
  { word: 'electrophysiological', hint: 'science' },
  { word: 'magnetohydrodynamics', hint: 'science' },
  { word: 'thermodynamically', hint: 'science' },
  { word: 'neurotransmission', hint: 'science' },

  { word: 'misunderstandingly', hint: 'concept' },
  { word: 'overgeneralization', hint: 'concept' },
  { word: 'counterintuitively', hint: 'concept' },
  { word: 'hyperconnectivity', hint: 'technology' },
  { word: 'deindustrialization', hint: 'concept' }
];
